version: '3.8'
services:
  influxdb:
    environment:
      - INFLUX_DB_INIT=true
      - INFLUX_DB_INIT_MODE=setup
      - INFLUX_DB_INIT_USERNAME=admin
      - INFLUX_DB_INIT_PASSWORD=${INFLUX_DB_INIT_PASSWORD}
      - INFLUX_DB_INIT_ORG=MidnightRider
      - INFLUX_DB_INIT_BUCKET=midnight_rider
      - INFLUX_DB_INIT_RETENTION=720h
      - INFLUX_DB_INIT_ADMIN_TOKEN=${INFLUX_DB_INIT_ADMIN_TOKEN}
